version: '3.1'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: "no"
    environment:
      discovery.type: single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elastic:9200
    depends_on: 
      - elastic
    ports:
      - 5601:5601
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml


volumes:
  data01: