version: '3.1'

services:

  db:
    image: postgres:11
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata11:/var/lib/postgresql/data
    ports:
      - 5052:5432

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 5051:8080

volumes:
  pgdata11: